yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Portfolio
site_url: https://wankhedeamey.github.io
theme:
  name: material
features:
  - navigation.top
extra_css:
  - stylesheets/extra.css

